name: krabalo
description: "Krabalo is an exciting and immersive gyroscope-controlled mobile game where players navigate a ball through challenging mazes, avoiding obstacles and enemies, to reach the goal."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flame: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
